### ISSUE TITLE
table mismatch in Jupyter Scripts

### ISSUE THREAD

**Issue by rcemper** [bdeboe/isc-taxi-demo#1]
the demo-GS22-* scripts show some mismatch
between description and executed SQL queried
and moreover a mismatch to available Tables in IRIS.
eg.  **NYTaxi.Rides2,, NYTaxi.Rides24M ,  NYTaxi**   

+colobench needs adjustment of connection

No showstopper, but rather distracting from the main message

A hint that results get generated asynchronously might adjust expectations.

**Comment by bdeboe** [comment]
Thanks for pointing out. I added a few comments to clarify. The colobench script in particular is not meant to be run and in there (in fully rendered form) for informational purposes only, unless you care to load 1B rows of data!

the fact that results get generated asynchronously is standard Jupyter
